monthly_expenses/config/routes.rb
Rails.application.routes.draw do

  root "homes#show"
  devise_for :users
  resources :items

end

monthly_expenses/app/models/item.rb
class Item < ActiveRecord::Base
  validates_exclusion_of :name, in: %w{ total Total TOTAL }
  belongs_to :user
end

monthly_expenses/app/models/total.rb
class Total
  attr_reader :price
  def initialize(items)
    @price = items.reduce(0) do |accumulator, item|
      accumulator += item.price
    end
  end

  def id
    0
  end

  def name
    "Total"
  end
end

monthly_expenses/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :items
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

monthly_expenses/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

monthly_expenses/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
    if user_signed_in?
      @items = current_user.items
      @total = Total.new(@items)
    end
  end
end

monthly_expenses/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
    @total = Total.new(@items)
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = current_user.items.build(item_params)
    
    respond_to do |format|
      if @item.save
        format.html { redirect_to root_path, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :price)
    end
end

monthly_expenses/app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

monthly_expenses/app/helpers/items_helper.rb
module ItemsHelper
end

monthly_expenses/app/views/application/_items_table.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td style="text-align: right"><%= number_to_currency item.price %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <tr>
      <td><b>TOTAL</b></td>
      <td style="text-align: right"><%= @total.price %></td>
    </tr>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

monthly_expenses/app/views/homes/show.html.erb
<h1>Monthly Expenses</h1>
<% if user_signed_in? %>
  <%= render "items_table", items: @items %>
<% end %>

monthly_expenses/app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

monthly_expenses/app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

monthly_expenses/app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Monthly Expenses</h1>

<%= render "items_table", items: @items %>

monthly_expenses/app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

monthly_expenses/app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

monthly_expenses/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MonthlyExpenses</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if user_signed_in? %>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <%= f.email_field :email, autofocus: true, placeholder: "Email" %>
      <%= f.password_field :password, autocomplete: "off", placeholder: "Password" %>
      <% if devise_mapping.rememberable? -%>
        <%= f.check_box :remember_me %>
        <%= f.label :remember_me %>
      <% end -%>
    <%= f.submit "Log in" %>
    <% end %>
    <%= link_to("Sign Up", new_user_registration_path) %>
  <% end %>

<%= yield %>

</body>
</html>